# Generated by Django 4.2.30 on 2026-05-14 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID Utilisateur 1xbet')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('wallet', models.CharField(choices=[('waafi', 'Waafi'), ('cac', 'CAC'), ('d-money', 'D-Money'), ('saba', 'Saba')], max_length=20, verbose_name='Wallet utilisé')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='ID de transaction')),
                ('screenshot', models.ImageField(upload_to='deposits/screenshots/', verbose_name="Capture d'écran")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (DJF)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note administrateur')),
            ],
            options={
                'verbose_name': 'Demande de dépôt',
                'verbose_name_plural': 'Demandes de dépôt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID Utilisateur 1xbet')),
                ('withdrawal_code', models.CharField(max_length=200, verbose_name='Code de retrait')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (DJF)')),
                ('wallet', models.CharField(choices=[('waafi', 'Waafi'), ('cac', 'CAC'), ('d-money', 'D-Money'), ('saba', 'Saba')], max_length=20, verbose_name='Wallet de réception')),
                ('wallet_number', models.CharField(max_length=30, verbose_name='Numéro du wallet')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note administrateur')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
